//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BikeApp.Models
{
    public partial class HiringInfo
    {
        public string sDate { get; set; }
        public string eDate { get; set; }
        public int CardInfo { get; set; }
        //[Key]
        public int FbikeId { get; set; }
    }
}
