//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAndBike
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string BikeModel { get; set; }
        public Nullable<int> BikeId { get; set; }
        public Nullable<System.DateTime> StardDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
